# Site settings
title: "Dražen Perić - Software Developer"
description: "10+ years experience in software development"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dražen Perić"
resume_title:                   "Software Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "peric.drazhen@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+386 30 635 519"
resume_contact_address:         ""

resume_header_location_info:  "Based in Ljubljana, Slovenia"
display_header_location_info: "true"

resume_header_contact_info:     "+386 30 635 519 • peric.drazhen@gmail.com"
display_header_contact_info:    "true"

current_status: "<strong>I am currently open to new job opportunities</strong>"

resume_header_intro: "<p>10+ years' experience in web development, where over the last couple of years, I have worked mostly with <strong>PHP</strong> (Laravel, Symfony2) and <strong>Ruby</strong> (Ruby On Rails) while developing back-end solutions. On the front-end side I have been mostly using pure <strong>JavaScript</strong>, <strong>Angular2</strong> and <strong>React</strong>. My relational database of choice is <strong>PostgreSQL</strong>, I am using <strong>Vagrant</strong> and <strong>Docker</strong> for development and I do not have any problems with writing scripts and helpers in <strong>Bash</strong>, <strong>Python</strong> or whatever will do the job. At the moment, I am learning the <strong>Go</strong> programming language and I would like to gain some experience with <strong>Vue.js</strong>.</p>

                      <p>I have experience with <strong>agile software development</strong> (Scrum, Kanban). I believe that a big and important part of software development is done before the actual coding process and that a proper development workflow can yield many benefits for both team and the product. I am competent in leading project sprints and planning as well as task management.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"
resume_looking_for_work_additional_info: "<p>I am searching for inspiring and interesting people to work with on a product that I can relate to. I am based in Ljubljana, I prefer flexible working and I do not have problems with working remotely. I also appreciate having time for myself and for the people around me, in order to have a balanced life. My current knowledge base largely depends on my experience in the past few years. Therefore, I do not regard my potential lack of knowledge about a specific topic at the moment as an issue, as I am able to learn new things easily, especially when they are challenging and fun.</p>"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_skills:          true
resume_section_education:       true
resume_section_projects:        true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
resume_section_languages:       true
resume_section_interests:       true
resume_section_courses:         true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/peric"
  resume_twitter_url:           "https://twitter.com/dperitch"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dperitch/"
  resume_instagram_url:         "https://instagram.com/dperitch"
  resume_website_url:           "https://echobehind.wordpress.com/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
