# Site settings
title: "Dražen Perić - Resume"
description: "A resume for myself."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dražen Perić"
resume_title:                   "Software Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "peric.drazhen@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+386 30 635 519"
resume_contact_address:         ""

resume_header_location_info:  "Based in Ljubljana, Slovenia"
display_header_location_info: "true"

resume_header_contact_info:     "+386 30 635 519 • peric.drazhen@gmail.com"
display_header_contact_info:    "true"

current_status: "<strong>I am open to new opportunities and available from 2nd of November 2018</strong>"

resume_header_intro: "<p>10+ years experience in web development where in the last couple of years I have been working mostly with <strong>PHP</strong> (Laravel, Symfony2) and <strong>Ruby</strong> (Ruby On Rails) while developing back-end solutions. On the front-end side I have been mostly using pure <strong>JavaScript</strong>, <strong>Angular2</strong> and <strong>React</strong>. My relational database of choice is <strong>PostgreSQL</strong>, I am using <strong>Vagrant</strong> and <strong>Docker</strong> for development, I love <strong>JetBrains</strong> IDE solutions and I don't have problems any problem with writing scripts and helpers in <strong>Bash</strong>, <strong>Python</strong> or whatever will do the job.</p>

                                <p>At the moment, I am learning <strong>Go</strong> programming language and I would like to gain some experience with <strong>Vue.js</strong> - preferably, this would also be my future stack of choice.</p>

                                <p>I have experience with <strong>agile software development</strong> (Scrum, Kanban). I believe that a big and important part of software development is done before the actual coding process and that a proper development workflow can bring a lot of benefits to the team and the product.</p>

                                <p>My current knowledge base largely depends on my experience in the past few years. Things are moving fast in the world of web development and you can easily lose track of some technology. But if you are an experienced developer you can easily get back on track or gain new experiences. Therefore, me not having knowledge about a specific thing at the moment should not be an issue in the near future since I am able to learn new things as long as it is fun and challenging.</p>

                                <p>I love software development - especially that feeling of building things from scratch and solving problems. And with more knowledge, you get more power and unlimited possibilities. Nevertheless, I like a dynamic lifestyle and therefore I am also passionate about other things that are not related to programming - technology, music, art and multiple indoor and outdoor activities are just some of them.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"
resume_looking_for_work_additional_info: "<p>I am searching for inspiring and interesting people to work with. I prefer working on a product that I can relate to and that I will enjoy to develop. I am based in Ljubljana, I prefer flexible working and I don't have problems with working remotely as long as it is between 8am and 5pm CET/CEST. I also appreciate having some time for myself and for the people around me, in order to have a balanced life.</p>"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_skills:          true
resume_section_education:       true
resume_section_projects:        true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
resume_section_languages:       true
resume_section_interests:       true
resume_section_courses:         true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/peric"
  resume_twitter_url:           "https://twitter.com/dperitch"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dperitch/"
  resume_instagram_url:         "https://instagram.com/dperitch"
  resume_website_url:           "https://echobehind.wordpress.com/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
